---
  - name: Update package list
    apt: update_cache=yes
    register: apt_result
    become_user: pi

  - name: Upgrade APT to the latest packages
    apt: upgrade=dist
    register: apt_result
    become_user: pi

  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become_user: pi

  - name: Install common packages
    apt:
      name: ['git', 'python', 'python3', 'python-pip', 'python3-pip', 'nfs-common', 
      'net-tools', 'htop', 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'curl', 'grep', 'unzip', 'zip', 'nano', 'grep', 'tree', 'ntp', 'ntpstat', 'ntpdate']
      update_cache: yes
      cache_valid_time: 86400
      state: latest
    become_user: pi

  - name: Autoremove unused packages
    apt: autoremove=yes
    changed_when: "'packages will be REMOVED' in apt_result.stdout"      
    become_user: pi
